job-advertisement-app/main/default/objects/Job_Advertisement__c/Job_Advertisement__c.object-meta.xml
<CustomObject>
    <label>Job Advertisement</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Advertisements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

job-advertisement-app/main/default/objects/Resume__c/Resume__c.object-meta.xml
<CustomObject>
    <label>Resume</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Resume Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resumes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

job-advertisement-app/main/default/objects/Resume__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

job-advertisement-app/main/default/objects/Resume__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

job-advertisement-app/main/default/objects/Resume__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

job-advertisement-app/main/default/objects/Resume__c/fields/Education__c.field-meta.xml
<CustomField>
    <fullName>Education__c</fullName>
    <label>Education</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GED/HS Diploma</fullName>
            </value>
            <value>
                <fullName>BA/BS</fullName>
            </value>
            <value>
                <fullName>MA/MS/MBA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>JD</fullName>
            </value>
            <value>
                <fullName>PhD</fullName>
            </value>
            <value>
                <fullName>Post Doc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

job-advertisement-app/main/default/objects/Resume__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/Province</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

job-advertisement-app/main/default/objects/Resume__c/fields/Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_Address__c</fullName>
    <label>Street Address</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

job-advertisement-app/main/default/objects/Resume__c/fields/Years_of_Experience__c.field-meta.xml
<CustomField>
    <fullName>Years_of_Experience__c</fullName>
    <label>Years of Experience</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

job-advertisement-app/main/default/objects/Resume__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

job-advertisement-app/main/default/objects/SentResume__c/SentResume__c.object-meta.xml
<CustomObject>
    <label>SentResume</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>SentResume Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SentResumes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

job-advertisement-app/main/default/objects/SentResume__c/fields/Job_Advertisement__c.field-meta.xml
<CustomField>
    <fullName>Job_Advertisement__c</fullName>
    <label>Job Advertisement</label>
    <referenceTo>Job_Advertisement__c</referenceTo>
    <relationshipLabel>SentResumes</relationshipLabel>
    <relationshipName>SentResumes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

job-advertisement-app/main/default/objects/SentResume__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>SentResumes</relationshipLabel>
    <relationshipName>SentResumes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

job-advertisement-app/main/default/classes/tests/TestDataFactory.cls
@isTest
public class TestDataFactory {

    public static Resume__c getRandomResume(Boolean ifInsert){
    Resume__c cv = new Resume__c(
        Age__c = 18,
        City__c='Kh',
        Country__c='US',	
        Education__c='MD',	
        Email__c='test@gmail.com',
        First_Name__c = 'Alex',
        Last_Name__c = 'Gudkov',	
        Phone__c = '0502209449',		
        Salary__c = 2500,	
        State_Province__c = 'NY',
        Street_Address__c = 'Str #55',
        Years_of_Experience__c	= 25,
        Zip_Postal_Code__c = '886589');
        if(ifInsert){
            insert cv;
        }
        return cv;
    }

    public static List<SentResume__c> getSentResumesByJobAdsAndCV(List<Job_Advertisement__c> jobAds, Resume__c resume, Boolean isInsert){
        Id resumeId = resume.id;
        List<SentResume__c> resumes = new List<SentResume__c>();
        for(Job_Advertisement__c jobAdv:jobAds){
            resumes.add(new SentResume__c(Job_Advertisement__c = jobAdv.id, Resume__c = resumeId));
        }
        if(isInsert){
            insert resumes;
        }
        return resumes;

    }

    public static List<Job_advertisement__c> prepareJobAdsList(Integer num, Boolean ifInsert){
     List<Job_Advertisement__c> jobAds = new List<Job_Advertisement__c>();
        for(Integer i=0;i<num;i++){
         jobAds.add(new Job_Advertisement__c(name='Vacancy'));
        }
        if(ifInsert){
          insert jobAds;
        }
        return jobAds;
    }
    
    public static Boolean listsAreEqual(List<WrappedJobAdvertisement> ads, List<String> jobTitles){
        if(ads.size()!=jobTitles.size()){
            return false;
         }        
        Integer index = 0;
        List<String> titles = new List<String>(jobTitles);
        for (WrappedJobAdvertisement adv:ads){           
            String advTitle = adv.adv.name; 
            for(Integer i=0;i<titles.size();i++){
                if(advTitle==titles.get(i)){
                    titles.remove(i);
                    break;                  
                } 
            }         
        }
       return titles.size()==0; 
    }  


    public static ContentVersion getContentVersion(String fileName, Blob fileContent){
        ContentVersion contentVersion = new ContentVersion();
        contentVersion.versionData = fileContent;
        contentVersion.title = fileName;
        contentVersion.pathOnClient =fileName;
        return contentVersion;       
    }


    public static ContentDocumentLink getContentDocLink(Id contentDocId, String shareType, String visibility, id linkedEntityId){
        ContentDocumentLink contentDocLink = new ContentDocumentLink();
        contentDocLink.ContentDocumentId = contentDocId;
        contentDocLink.LinkedEntityId = linkedEntityId;
        contentDocLink.ShareType = shareType; 
        contentDocLink.Visibility = visibility;
        return contentDocLink;
    }

    
    
    public class ExpandedStringList {
        private List<String> values;
        
        public ExpandedStringList(){
            values = new List<String>();
        }
        
        public ExpandedStringList(String value){
            values = new List<String>();
            values.add(value);
        }
        
        public ExpandedStringList add(String value){
            values.add(value);
            return this;
        }
        
        public List<String> getList(){
            return values;
        }
        
    }

    

}