job-advertisement-app/main/default/objects/Job_Advertisement__c/Job_Advertisement__c.object-meta.xml
<CustomObject>
    <label>Job Advertisement</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Advertisements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

job-advertisement-app/main/default/objects/Resume__c/Resume__c.object-meta.xml
<CustomObject>
    <label>Resume</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Resume Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resumes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

job-advertisement-app/main/default/objects/Resume__c/fields/PhotoFileId__c.field-meta.xml
<CustomField>
    <fullName>PhotoFileId__c</fullName>
    <label>PhotoFileId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

job-advertisement-app/main/default/objects/SentResume__c/SentResume__c.object-meta.xml
<CustomObject>
    <label>SentResume</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>SentResume Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SentResumes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

job-advertisement-app/main/default/objects/SentResume__c/fields/Job_Advertisement__c.field-meta.xml
<CustomField>
    <fullName>Job_Advertisement__c</fullName>
    <label>Job Advertisement</label>
    <referenceTo>Job_Advertisement__c</referenceTo>
    <relationshipLabel>SentResumes</relationshipLabel>
    <relationshipName>SentResumes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

job-advertisement-app/main/default/objects/SentResume__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>SentResumes</relationshipLabel>
    <relationshipName>SentResumes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

job-advertisement-app/main/default/classes/core/controllers/CVcreationController.cls
public class CVcreationController {
    public WrappedCV wrappedCV{get;set;}
    private Ivalidator validator;
    private IresumeService cvService; 
    private IfileService fileService;
    private ControllerContext context;
    
    public CVcreationController(){
        this(new WrappedCvValidator(), new ResumeServiceImpl(), new BaseFileService());
    }
    
    public CVcreationController(Ivalidator validator, IresumeService cvService, IfileService fileService){
        this.validator = validator;
        this.cvService = cvService;
        this.fileService = fileService;
        wrappedCV = new WrappedCV();
        context = ControllerContext.getInstance();
    }

   
    public PageReference applyCV(){  
        List<WrappedJobAdvertisement> selectedwrappedAds =
        (List<WrappedJobAdvertisement>) context.get(Constants.CONTEXT_SELECTED_JOB_ADV);
        List<String> errors = validator.validate(wrappedCV);
        if(errors.isEmpty()){          
            if(!selectedwrappedAds.isEmpty()){                
                Map<Id, Job_Advertisement__c> selectedAds = WrappedJobAdvUtils.extractJobAdsAsMap(selectedwrappedAds);
                List<SentResume__c> sentResumes = getSentResumes(selectedAds.keySet(), wrappedCV.cv.Email__c);                 
                if(sentResumes.isEmpty()){
                    Savepoint savePoint = Database.setSavepoint();
                    try{
                        cvService.addResumeWithJobAds(wrappedCV.cv,selectedAds.values());                        
                        cvService.attachPhotoToResume(wrappedCV.cv, savePhoto());
                        sendNotification(selectedAds.values(), wrappedCV.cv.Email__c);
                        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, System.Label.Msg_success_cv_send));
                        wrappedCV.clearPhotoDetails();
                        PageReference pageRef = Page.JobAdvertisementSite;
                        pageRef.setRedirect(true);
                        return pageRef;
                       

                    }
                    catch(ResumeServiceImplException exc){
                        Database.rollback(savePoint);
                        addError(System.Label.Exc_send_cv);                                           
                    } 
                    catch(ClearFileException exc){
                        Database.rollback(savePoint);
                        addError(System.Label.Exc_save_photo);
                    }
                    catch(SaveFileException exc){
                        Database.rollback(savePoint);
                        addError(System.Label.Exc_save_photo);
                    }                    
                }
                else{
                    addErrors(System.Label.Error_already_sent_posns, sentResumes);
                }               
            }
            else{
                addError(System.Label.Error_no_selected_ads);
            }            
        }
        else{
            addErrors(errors);    
        }       
        wrappedCV.clearPhotoDetails();
        return null;
               
    }

    private void sendNotification(List<Job_Advertisement__c> jobAds, String mailAddress){
        String mailBody = Constants.EMAIL_SEND_CV_NOTIFICATION_BODY_HEADER;
        for(Job_Advertisement__c jobAdv:jobAds){          
            mailBody+=jobAdv.name+'\n';
        }
        EmailManager.EmailAddress addresses = new EmailManager.EmailAddress();
        addresses.to.add(mailAddress); 
        EmailManager.sendMail(addresses, Constants.EMAIL_SEND_CV_NOTIFICATION_SUBJECT, mailBody); 
    }

    private String savePhoto(){
        Resume__c resume = [SELECT PhotoFileId__c FROM Resume__c WHERE id = :wrappedCV.cv.id].get(0);
           if(!String.isBlank(resume.PhotoFileId__c)){
               fileService.removeFile(resume.PhotoFileId__c);
            }
            return fileService.saveFile(wrappedCV.photoName, wrappedCV.photoAsString, 'I', 'AllUsers', resume.id);
    }
       
    private List<SentResume__c> getSentResumes(Set<Id> selectedWrappedAdsIds, String cvEmail){
        return [SELECT Job_Advertisement__r.id, Job_Advertisement__r.name 
                FROM SentResume__c 
                WHERE Job_Advertisement__c IN :selectedWrappedAdsIds AND Resume__r.email__c = :cvEmail];
    }
    
    private void addError(String msg){
       ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, msg)); 
    }
    
    private void addErrors(List<String> msgs){
        for(String msg:msgs){
                  ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, msg));  
        } 
    }
    
    private void addErrors(String title, List<SentResume__c> sentResumes){
        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,title));
                    for(SentResume__c sentCV:sentResumes){
                        ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,sentCV.Job_Advertisement__r.name));                       
                    } 
    } 
    
}