job-advertisement-app/main/default/objects/Job_Advertisement__c/Job_Advertisement__c.object-meta.xml
<CustomObject>
    <label>Job Advertisement</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Advertisements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

job-advertisement-app/main/default/objects/Job_Advertisement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>On hold</fullName>
            </value>
            <value>
                <fullName>Archive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

job-advertisement-app/main/default/objects/Resume__c/Resume__c.object-meta.xml
<CustomObject>
    <label>Resume</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Resume Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resumes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

job-advertisement-app/main/default/objects/SentResume__c/SentResume__c.object-meta.xml
<CustomObject>
    <label>SentResume</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>SentResume Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SentResumes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

job-advertisement-app/main/default/objects/SentResume__c/fields/Job_Advertisement__c.field-meta.xml
<CustomField>
    <fullName>Job_Advertisement__c</fullName>
    <label>Job Advertisement</label>
    <referenceTo>Job_Advertisement__c</referenceTo>
    <relationshipLabel>SentResumes</relationshipLabel>
    <relationshipName>SentResumes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

job-advertisement-app/main/default/objects/SentResume__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>SentResumes</relationshipLabel>
    <relationshipName>SentResumes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

job-advertisement-app/main/default/classes/tests/trigger_helper/JobAdvertisementTriggerHelperTest.cls
@isTest
private class JobAdvertisementTriggerHelperTest {
    
    @isTest private static void test_manageSentResumesRemovalCorrectly() {
        //Given
        Resume__c cv = TestDataFactory.getRandomResume(true);
        Map<Id, Job_Advertisement__c> oldJobAds = new Map<Id,Job_Advertisement__c>(TestDataFactory.prepareJobAdsList(5, true));
        List<SentResume__c> sentResumes = TestDataFactory.getSentResumesByJobAdsAndCV(oldJobAds.values(),cv,true);
        Map<Id,Job_Advertisement__c> newJobAds = new Map<Id,Job_Advertisement__c>([SELECT Status__c FROM Job_Advertisement__c]);
        Job_Advertisement__c jobAdvToCheck = newJobAds.values().get(0);
        System.assertEquals(1, [SELECT COUNT() FROM SentResume__c WHERE Job_Advertisement__c=:jobAdvToCheck.id]);
        jobAdvToCheck.Status__c = 'Archive';

        //When
        Test.startTest();
        JobAdvertisementTriggerHelper.manageSentResumesRemoval(oldJobAds, newJobAds);
        Test.stopTest();

        //Then
        System.assertEquals(0,[SELECT COUNT() FROM SentResume__c WHERE Job_Advertisement__c=:jobAdvToCheck.id]);
    }

    @isTest private static void test_manageSentResumesRemovalNoRelevantJobAds() {
        //Given
        Integer jobAdvNum = 5;
        Resume__c cv = TestDataFactory.getRandomResume(true);
        Map<Id, Job_Advertisement__c> oldJobAds = new Map<Id,Job_Advertisement__c>(TestDataFactory.prepareJobAdsList(jobAdvNum, true));
        List<SentResume__c> sentResumes = TestDataFactory.getSentResumesByJobAdsAndCV(oldJobAds.values(),cv,true);
        Map<Id,Job_Advertisement__c> newJobAds = new Map<Id,Job_Advertisement__c>([SELECT Status__c FROM Job_Advertisement__c]);
        Job_Advertisement__c jobAdvToCheck = newJobAds.values().get(0);
        System.assertEquals(1, [SELECT COUNT() FROM SentResume__c WHERE Job_Advertisement__c=:jobAdvToCheck.id]);
        jobAdvToCheck.Status__c = 'On hold';

        //When
        Test.startTest();
        JobAdvertisementTriggerHelper.manageSentResumesRemoval(oldJobAds, newJobAds);
        Test.stopTest();

        //Then
        System.assertEquals(jobAdvNum,[SELECT COUNT() FROM SentResume__c]);
        System.assertEquals(1,[SELECT COUNT() FROM SentResume__c WHERE Job_Advertisement__c=:jobAdvToCheck.id]);
    }
     @isTest private static void test_manageSentResumesRemovalBulk() {
        //Given
        Integer jobAdvNum = 200;
        Resume__c cv = TestDataFactory.getRandomResume(true);
        Map<Id, Job_Advertisement__c> oldJobAds = new Map<Id,Job_Advertisement__c>(TestDataFactory.prepareJobAdsList(jobAdvNum, true));
        List<SentResume__c> sentResumes = TestDataFactory.getSentResumesByJobAdsAndCV(oldJobAds.values(),cv,true);
        Map<Id,Job_Advertisement__c> newJobAds = new Map<Id,Job_Advertisement__c>([SELECT Status__c FROM Job_Advertisement__c]);
        for(Id jobAdvId:newJobAds.keySet()){
           newJobAds.get(jobAdvId).Status__c = 'Archive'; 
        }        
        System.assertEquals(jobAdvNum, [SELECT COUNT() FROM SentResume__c]);

        //When
        Test.startTest();
        JobAdvertisementTriggerHelper.manageSentResumesRemoval(oldJobAds, newJobAds);
        Test.stopTest();

        //Then
        System.assertEquals(0,[SELECT COUNT() FROM SentResume__c]);
    }
}