job-advertisement-app/main/default/objects/Job_Advertisement__c/Job_Advertisement__c.object-meta.xml
<CustomObject>
    <label>Job Advertisement</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Advertisements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

job-advertisement-app/main/default/objects/Resume__c/Resume__c.object-meta.xml
<CustomObject>
    <label>Resume</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Resume Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resumes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

job-advertisement-app/main/default/objects/Resume__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

job-advertisement-app/main/default/objects/Resume__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

job-advertisement-app/main/default/objects/Resume__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

job-advertisement-app/main/default/objects/Resume__c/fields/Education__c.field-meta.xml
<CustomField>
    <fullName>Education__c</fullName>
    <label>Education</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GED/HS Diploma</fullName>
            </value>
            <value>
                <fullName>BA/BS</fullName>
            </value>
            <value>
                <fullName>MA/MS/MBA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>JD</fullName>
            </value>
            <value>
                <fullName>PhD</fullName>
            </value>
            <value>
                <fullName>Post Doc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

job-advertisement-app/main/default/objects/Resume__c/fields/PhotoFileId__c.field-meta.xml
<CustomField>
    <fullName>PhotoFileId__c</fullName>
    <label>PhotoFileId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

job-advertisement-app/main/default/objects/Resume__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/Province</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

job-advertisement-app/main/default/objects/Resume__c/fields/Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_Address__c</fullName>
    <label>Street Address</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

job-advertisement-app/main/default/objects/Resume__c/fields/Years_of_Experience__c.field-meta.xml
<CustomField>
    <fullName>Years_of_Experience__c</fullName>
    <label>Years of Experience</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

job-advertisement-app/main/default/objects/Resume__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

job-advertisement-app/main/default/objects/SentResume__c/SentResume__c.object-meta.xml
<CustomObject>
    <label>SentResume</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>SentResume Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SentResumes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

job-advertisement-app/main/default/objects/SentResume__c/fields/Job_Advertisement__c.field-meta.xml
<CustomField>
    <fullName>Job_Advertisement__c</fullName>
    <label>Job Advertisement</label>
    <referenceTo>Job_Advertisement__c</referenceTo>
    <relationshipLabel>SentResumes</relationshipLabel>
    <relationshipName>SentResumes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

job-advertisement-app/main/default/objects/SentResume__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>SentResumes</relationshipLabel>
    <relationshipName>SentResumes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

job-advertisement-app/main/default/classes/core/utils/Utils.cls
public class Utils {
    
    public static String jobAdsList2JsonAsString(Map<String,Job_Advertisement__c> jobAds){       
        return JSON.serialize(jobAds);
    }
     
    public static Map<String,Job_Advertisement__c> blob2JobAdsWithIds(Blob body){
        Map<String,Job_Advertisement__c> jobAds = 
            (Map<String,Job_Advertisement__c>) JSON.deserialize(body.toString(), Map<String,Job_Advertisement__c>.class);
        return jobAds;
    }
    
    public static Map<String,Job_Advertisement__c> blob2JobAdsWithIds(String body){
        Map<String,Job_Advertisement__c> jobAds = 
            (Map<String,Job_Advertisement__c>) JSON.deserialize(body, Map<String,Job_Advertisement__c>.class);
        return jobAds;
    }

    public static List<ResumeDTO> resumes2resumesDTO(List<Resume__c> resumes, List<ContentVersion> contentVersions){
        Map<Id, ContentVersion> photoDetails = new Map<Id, ContentVersion>(contentVersions);
        List<ResumeDTO> resumesDto = new List<ResumeDTO>();
        for(Resume__c resume:resumes){
            resumesDto.add(resume2resumeDto(resume, photoDetails.get(resume.PhotoFileId__c)));
        }
        return resumesDto;

    }

    public static ResumeDTO resume2resumeDto(Resume__c resume, ContentVersion contentVersion){
       ResumeDTO resumeDto = new ResumeDTO();    
       resumeDto.firstName = resume.First_Name__c;
       resumeDto.lastName = resume.Last_Name__c;
       resumeDto.phone = resume.Phone__c;
       resumeDto.email = resume.Email__c;
       resumeDto.education = resume.Education__c;
       resumeDto.currentlyEmployed = resume.Currently_Employed__c;
       resumeDto.country = resume.Country__c;
       resumeDto.city = resume.City__c;
       resumeDto.state = resume.State_Province__c;
       resumeDto.zipCode = resume.Zip_Postal_Code__c;
       resumeDto.street = resume.Street_Address__c;
       resumeDto.additionalInformation = resume.Additional_Info__c; 
       resumeDto.salary = String.valueOf(resume.Salary__c);
       resumeDto.experienceYears = String.valueOf(resume.Years_of_Experience__c);
       resumeDto.age = String.valueOf(resume.Age__c);      
       if(contentVersion!=null){
           resumeDto.photo = EncodingUtil.base64Encode(contentVersion.versionData);
           resumeDto.photoName = contentVersion.title;
       }
        for (SentResume__c sentResume : resume.SentResumes__r){
            resumeDto.jobAdIds.add(sentResume.Job_Advertisement__r.id); 
        }
        return resumeDto;
    }
    
}