job-advertisement-app/main/default/objects/Job_Advertisement__c/Job_Advertisement__c.object-meta.xml
<CustomObject>
    <label>Job Advertisement</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Advertisements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

job-advertisement-app/main/default/objects/Resume__c/Resume__c.object-meta.xml
<CustomObject>
    <label>Resume</label>
    <nameField>
        <displayFormat>RES-{0000}</displayFormat>
        <label>Resume Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Resumes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

job-advertisement-app/main/default/objects/Resume__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <label>Age</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

job-advertisement-app/main/default/objects/Resume__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

job-advertisement-app/main/default/objects/Resume__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

job-advertisement-app/main/default/objects/Resume__c/fields/Education__c.field-meta.xml
<CustomField>
    <fullName>Education__c</fullName>
    <label>Education</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GED/HS Diploma</fullName>
            </value>
            <value>
                <fullName>BA/BS</fullName>
            </value>
            <value>
                <fullName>MA/MS/MBA</fullName>
            </value>
            <value>
                <fullName>MD</fullName>
            </value>
            <value>
                <fullName>JD</fullName>
            </value>
            <value>
                <fullName>PhD</fullName>
            </value>
            <value>
                <fullName>Post Doc</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

job-advertisement-app/main/default/objects/Resume__c/fields/PhotoFileId__c.field-meta.xml
<CustomField>
    <fullName>PhotoFileId__c</fullName>
    <label>PhotoFileId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

job-advertisement-app/main/default/objects/Resume__c/fields/State_Province__c.field-meta.xml
<CustomField>
    <fullName>State_Province__c</fullName>
    <label>State/Province</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

job-advertisement-app/main/default/objects/Resume__c/fields/Street_Address__c.field-meta.xml
<CustomField>
    <fullName>Street_Address__c</fullName>
    <label>Street Address</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

job-advertisement-app/main/default/objects/Resume__c/fields/Years_of_Experience__c.field-meta.xml
<CustomField>
    <fullName>Years_of_Experience__c</fullName>
    <label>Years of Experience</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

job-advertisement-app/main/default/objects/Resume__c/fields/Zip_Postal_Code__c.field-meta.xml
<CustomField>
    <fullName>Zip_Postal_Code__c</fullName>
    <label>Zip/Postal Code</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

job-advertisement-app/main/default/objects/SentResume__c/SentResume__c.object-meta.xml
<CustomObject>
    <label>SentResume</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>SentResume Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SentResumes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

job-advertisement-app/main/default/objects/SentResume__c/fields/Job_Advertisement__c.field-meta.xml
<CustomField>
    <fullName>Job_Advertisement__c</fullName>
    <label>Job Advertisement</label>
    <referenceTo>Job_Advertisement__c</referenceTo>
    <relationshipLabel>SentResumes</relationshipLabel>
    <relationshipName>SentResumes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

job-advertisement-app/main/default/objects/SentResume__c/fields/Resume__c.field-meta.xml
<CustomField>
    <fullName>Resume__c</fullName>
    <label>Resume</label>
    <referenceTo>Resume__c</referenceTo>
    <relationshipLabel>SentResumes</relationshipLabel>
    <relationshipName>SentResumes</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

job-advertisement-app/main/default/classes/tests/utils/UtilsTest.cls
@isTest
private class UtilsTest {
    
    @isTest private static void test_resume2resumeDto(){
        //Given
        Blob photoContent = Blob.valueOf('test');
        String photoName = 'test.gif';
        Integer jobAdvNum = 3;
        Resume__c cv = TestDataFactory.getRandomResume(true);
        ContentVersion contentVersion = getContentVersion(photoName, photoContent,cv.id);
        List<Job_advertisement__c> jobAds = TestDataFactory.prepareJobAdsList(jobAdvNum,true);
        List<SentResume__c> sentCVs = TestDataFactory.getSentResumesByJobAdsAndCV(jobAds, cv, true);
        cv = getActualCV();

        //When
        Test.startTest();
        ResumeDTO resumeDto = Utils.resume2resumeDto(cv, contentVersion);
        Test.stopTest();

        //Then
        System.assertEquals(cv.Age__c, Decimal.valueOf(resumeDto.age));
        System.assertEquals(cv.City__c, resumeDto.city);
        System.assertEquals(cv.Country__c, resumeDto.country);
        System.assertEquals(cv.Education__c, resumeDto.education);
        System.assertEquals(cv.Email__c, resumeDto.email);
        System.assertEquals(cv.First_Name__c, resumeDto.firstName);
        System.assertEquals(cv.Last_Name__c, resumeDto.lastName);
        System.assertEquals(cv.Phone__c, resumeDto.phone);		
        System.assertEquals(cv.Salary__c, Decimal.valueOf(resumeDto.salary));
        System.assertEquals(cv.State_Province__c, resumeDto.state);
        System.assertEquals(cv.Street_Address__c , resumeDto.street);
        System.assertEquals(cv.Years_of_Experience__c, Decimal.valueOf(resumeDto.experienceYears));
        System.assertEquals(cv.Zip_Postal_Code__c, resumeDto.zipCode);
        System.assertEquals(EncodingUtil.base64Encode(photoContent), resumeDto.photo);
        System.assertEquals(photoName, resumeDto.photoName);
        Set<String> jobAdvIds = new Set<String>(resumeDto.jobAdIds);
        System.assertEquals(jobAds.size(),jobAdvIds.size());

        Boolean testResult = true;
        for(Job_advertisement__c jobadv:jobAds){
            if(!jobAdvIds.contains(jobAdv.id)){
               testResult = false; 
            }
        }
        System.assert(testResult);
    }

    @isTest private static void test_resumes2resumesDTO(){
        //Given
        Blob photoContent = Blob.valueOf('test');
        String photoName = 'test.gif';
        Integer jobAdvNum = 3;
        Resume__c cv = TestDataFactory.getRandomResume(true);
        cv.Salary__c = null;
        ContentVersion contentVersion = getContentVersion(photoName, photoContent,cv.id);
        List<Job_advertisement__c> jobAds = TestDataFactory.prepareJobAdsList(jobAdvNum,true);
        List<SentResume__c> sentCVs = TestDataFactory.getSentResumesByJobAdsAndCV(jobAds, cv, true);
        cv = getActualCV();
        cv.PhotoFileId__c =contentVersion.id;

        //When
        Test.startTest();
        List<ResumeDTO> resumesDto = Utils.resumes2resumesDTO(new List<Resume__c>{cv}, new List<ContentVersion>{contentVersion});
        Test.stopTest();

        //Then
        System.assertEquals(1, resumesDto.size());
        ResumeDTO resumeDto = resumesDto.get(0);
        System.assertEquals(cv.Age__c, Decimal.valueOf(resumeDto.age));
        System.assertEquals(cv.City__c, resumeDto.city);
        System.assertEquals(cv.Country__c, resumeDto.country);
        System.assertEquals(cv.Education__c, resumeDto.education);
        System.assertEquals(cv.Email__c, resumeDto.email);
        System.assertEquals(cv.First_Name__c, resumeDto.firstName);
        System.assertEquals(cv.Last_Name__c, resumeDto.lastName);
        System.assertEquals(cv.Phone__c, resumeDto.phone);		
        System.assertEquals(cv.Salary__c, Decimal.valueOf(resumeDto.salary));
        System.assertEquals(cv.State_Province__c, resumeDto.state);
        System.assertEquals(cv.Street_Address__c , resumeDto.street);
        System.assertEquals(cv.Years_of_Experience__c, Decimal.valueOf(resumeDto.experienceYears));
        System.assertEquals(cv.Zip_Postal_Code__c, resumeDto.zipCode);
        System.assertEquals(EncodingUtil.base64Encode(photoContent), resumeDto.photo);
        System.assertEquals(photoName, resumeDto.photoName);
        Set<String> jobAdvIds = new Set<String>(resumeDto.jobAdIds);
        System.assertEquals(jobAds.size(),jobAdvIds.size());

        Boolean testResult = true;
        for(Job_advertisement__c jobadv:jobAds){
            if(!jobAdvIds.contains(jobAdv.id)){
               testResult = false; 
            }
        }
        System.assert(testResult);
    }

    private static Resume__c getActualCV(){
        return Database.query('SELECT (SELECT Job_Advertisement__r.id FROM SentResumes__r),'+
        'First_Name__c,Last_Name__c,Age__c,Phone__c,Email__c,Education__c,'+
        'Currently_Employed__c,Country__c,City__c,State_Province__c,Zip_Postal_Code__c,'+
        'Street_Address__c,Salary__c,Years_of_Experience__c,Additional_Info__c,PhotoFileId__c FROM Resume__c');
    }

    private static ContentVersion getContentVersion(String fileName, Blob fileContent, id relatedEntityId){
        ContentVersion contentVersion = TestDataFactory.getContentVersion(fileName, fileContent);
        insert contentVersion;
        Id contentDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:contentVersion.Id].ContentDocumentId;
        ContentDocumentLink contentDocLink = TestDataFactory.getContentDocLink(contentDocId, 'I', 'AllUsers', relatedEntityId);
        insert contentDocLink;
        return contentVersion;
    }
}