job-advertisement-app/main/default/objects/Job_Advertisement__c/Job_Advertisement__c.object-meta.xml
<CustomObject>
    <label>Job Advertisement</label>
    <nameField>
        <label>Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Job Advertisements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

job-advertisement-app/main/default/objects/Job_Advertisement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>On hold</fullName>
            </value>
            <value>
                <fullName>Archive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

job-advertisement-app/main/default/objects/SentResume__c/SentResume__c.object-meta.xml
<CustomObject>
    <label>SentResume</label>
    <nameField>
        <displayFormat>SR-{0000}</displayFormat>
        <label>SentResume Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SentResumes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

job-advertisement-app/main/default/objects/SentResume__c/fields/Job_Advertisement__c.field-meta.xml
<CustomField>
    <fullName>Job_Advertisement__c</fullName>
    <label>Job Advertisement</label>
    <referenceTo>Job_Advertisement__c</referenceTo>
    <relationshipLabel>SentResumes</relationshipLabel>
    <relationshipName>SentResumes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

job-advertisement-app/main/default/classes/core/trigger_helpers/JobAdvertisementTriggerHelper.cls
public class JobAdvertisementTriggerHelper {
    
    public static void manageSentResumesRemoval(Map<Id, Job_Advertisement__c> oldJobAds, Map<Id, Job_Advertisement__c> newJobAds){
        Map<String, Set<String>> fieldValues = new Map<String, Set<String>>();
        fieldValues.put('Status__c',new Set<String>{'Archive'});
        TriggerUtils.RecordFilter filter = new TriggerUtils.RecordFilter (oldJobAds, newJobAds, fieldValues,'Status__c');        
        List<Job_Advertisement__c> jobAds = filter.getFilteredList();    
        if(!jobAds.isEmpty()){
            Map<Id, Job_Advertisement__c> jobAdvMap = new Map<Id, Job_Advertisement__c>(jobAds);
            try{
                deleteSentResume(new List<Id>(jobAdvMap.keySet()));
            }
            catch(DMLException exc){
                throw new SentResumeRemovalException('Error to remove sent resumes',exc);
            } 
        } 
    }

    private static void deleteSentResume(List<Id> jobAdvId){
        List<SentResume__c> sentResumes = [SELECT id FROM SentResume__c WHERE Job_Advertisement__c IN :jobAdvId];
        if (!sentResumes.isEmpty()){
            delete sentResumes;
        }
    }

    public class SentResumeRemovalException extends Exception{}


}